# Generated by Django 3.0.5 on 2020-04-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_item',
            old_name='item_id',
            new_name='item',
        ),
    ]
