# Generated by Django 3.0.5 on 2020-04-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200422_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='extras',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='size',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
