# Generated by Django 3.0.5 on 2020-04-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200423_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
    ]
