# Generated by Django 3.0.5 on 2020-04-23 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='processed',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='order',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='completed_date',
            field=models.DateField(null=True),
        ),
    ]
