# Generated by Django 3.0.5 on 2020-04-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200423_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='check_out_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
