# Generated by Django 3.0.5 on 2020-04-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200423_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_count',
            field=models.IntegerField(default=0),
        ),
    ]
